In [2]:
import torch

In [13]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9627, 0.2014, 0.6086],
        [0.5028, 0.3938, 0.5051],
        [0.7652, 0.5573, 0.9104],
        [0.5029, 0.9862, 0.8268],
        [0.9558, 0.1443, 0.8828]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
import torch
import time

print(torch.__version__)        # 返回pytorch的版本
print(torch.cuda.is_available())        # 当CUDA可用时返回True

a = torch.randn(10000, 1000)    # 返回10000行1000列的张量矩阵
b = torch.randn(1000, 2000)     # 返回1000行2000列的张量矩阵

t0 = time.time()        # 记录时间
c = torch.matmul(a, b)      # 矩阵乘法运算
t1 = time.time()        # 记录时间
print(a.device, t1 - t0, c.norm(2))     # c.norm(2)表示矩阵c的二范数

device = torch.device('cuda')       # 用GPU来运行
a = a.to(device)
b = b.to(device)

# 初次调用GPU，需要数据传送，因此比较慢
t0 = time.time()
c = torch.matmul(a, b)
t2 = time.time()
print(a.device, t2 - t0, c.norm(2))

# 这才是GPU处理数据的真实运行时间，当数据量越大，GPU的优势越明显
t0 = time.time()
c = torch.matmul(a, b)
t2 = time.time()
print(a.device, t2 - t0, c.norm(2))


1.7.1
True
cpu 0.15855002403259277 tensor(141040.8281)
cuda:0 0.744037389755249 tensor(141444.6875, device='cuda:0')
cuda:0 0.005983829498291016 tensor(141444.6875, device='cuda:0')


In [20]:
x = x.new_ones(5, 3, dtype=torch.float64) # 􁬬􀢧􁌱tensor􁼕􁦊torch.dtype􀞾torch.device􀙍􀹍􁍘􀝶􁌱

print(x)
x = torch.randn_like(x, dtype=torch.float) # 􀳰􀨧􀷛􁌱􀷄􀴝􁔄􀣳
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1782, -0.9524, -0.7537],
        [ 1.8813,  0.2459, -0.1455],
        [-1.1757,  0.6135,  0.1754],
        [-1.0088, -1.8118,  0.2841],
        [-1.8696, -0.8414, -0.8786]])


In [21]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [26]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 1.8218,  2.0476,  2.2463],
        [ 1.8813,  0.2459, -0.1455],
        [-1.1757,  0.6135,  0.1754],
        [-1.0088, -1.8118,  0.2841],
        [-1.8696, -0.8414, -0.8786]])
tensor([[0.7332, 0.1354, 0.1795],
        [0.3780, 0.4696, 0.6099],
        [0.0035, 0.1941, 0.2777],
        [0.3315, 0.9031, 0.6155],
        [0.8316, 0.7169, 0.1617]])
tensor([[ 2.5549,  2.1830,  2.4258],
        [ 2.2593,  0.7155,  0.4644],
        [-1.1722,  0.8076,  0.4530],
        [-0.6774, -0.9087,  0.8996],
        [-1.0380, -0.1245, -0.7169]])


In [27]:
y = x[0, :]
y += 1
print(y)
print(x[0,:])
print(x)

tensor([2.8218, 3.0476, 3.2463])
tensor([2.8218, 3.0476, 3.2463])
tensor([[ 2.8218,  3.0476,  3.2463],
        [ 1.8813,  0.2459, -0.1455],
        [-1.1757,  0.6135,  0.1754],
        [-1.0088, -1.8118,  0.2841],
        [-1.8696, -0.8414, -0.8786]])


In [31]:
y = x.view(15)
z = x.view(-1, 5) # -1􀲅􀳰􁌱􁖌􀬶􀝢􀕦􀻑􀴝􀙌􀕜􁖌􀬶􁌱􊧊􀴵􀚊􀹶
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[ 2.8218,  3.0476,  3.2463],
        [ 1.8813,  0.2459, -0.1455],
        [-1.1757,  0.6135,  0.1754],
        [-1.0088, -1.8118,  0.2841],
        [-1.8696, -0.8414, -0.8786]])
tensor([ 2.8218,  3.0476,  3.2463,  1.8813,  0.2459, -0.1455, -1.1757,  0.6135,
         0.1754, -1.0088, -1.8118,  0.2841, -1.8696, -0.8414, -0.8786])
tensor([[ 2.8218,  3.0476,  3.2463,  1.8813,  0.2459],
        [-0.1455, -1.1757,  0.6135,  0.1754, -1.0088],
        [-1.8118,  0.2841, -1.8696, -0.8414, -0.8786]])
